# Generated by Django 3.0.7 on 2020-06-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts", name="votes", field=models.IntegerField(null=True),
        ),
    ]
