# Generated by Django 3.0.7 on 2020-06-18 22:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0004_comment"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="votes",),
        migrations.AddField(
            model_name="post",
            name="votes",
            field=models.ManyToManyField(
                related_name="user_votes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
